<?php


/** ---------------------------------------
* DASHBOARD BLOCK
------------------------------------------- */

/**
 * Implements hook_block_info().
 */
function data_dashboard_block_info() {
  $blocks['data_dashboard'] = array(
    'info' => t('Data Dashboard'),
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function data_dashboard_block_view($delta='') {
  $module_path = drupal_get_path('module', 'data_dashboard');
  $css_options = array(
    'group' => CSS_DEFAULT, 
    'type' => 'file', 
    'every_page' => FALSE
  );
  $js_options = array(
    'group' => JS_DEFAULT, 
    'type' => 'file', 
    'every_page' => FALSE
  );

  drupal_add_css($module_path . '/css/app.css', $css_options);
  drupal_add_js($module_path . '/lib/jquery.waitforimages.min.js', $js_options);
  drupal_add_js($module_path . '/lib/idle.js', $js_options);
  drupal_add_js($module_path . '/strings/de-DE/i18n.js', $js_options);
  drupal_add_js($module_path . '/js/config.js', $js_options);
  drupal_add_js($module_path . '/js/app.js', $js_options);
  drupal_add_js($module_path . '/js/buildedit.js', $js_options);
  drupal_add_js($module_path . '/js/buildlist.js', $js_options);

  drupal_add_js(array('data_dashboard' => array('basePath' => $module_path . '/')), 'setting');

  $block = array();
  
  switch($delta) {
    case 'data_dashboard' :
      $block['content'] = data_dashboard_container();
      break;
  }
  
  return $block;
}


function data_dashboard_container() {
  $block = array();


  // Block output in HTML with div wrapper
  $block = array(
    'message' => array(
      '#type' => 'markup',
      '#markup' => '<div id="board"><section class="endcard"></section></div>',
    ),
  );

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function data_dashboard_block_configure($delta = '') {
  $form = array();
  switch ($delta) {
    case 'data_dashboard':
      $form['waben_list'] = array(
        '#type' => 'textfield',
        '#title' => t('Angezeigte Waben'),
        '#default_value' => variable_get('waben_list'),
      );
      break;
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function data_dashboard_block_save($delta = '', $edit = array()) {
  switch ($delta) {
    case 'data_dashboard':   
      variable_set('waben_list', $edit['waben_list']);
      break;
  }
}
/**********************************
* JSON Export
************************************/

function data_dashboard_menu() {
  error_log("data_dashboard_menu");
  $items['wabe/%/json'] = array(
    'access callback' => true , // available to all
    'page callback' => 'data_dashboard_export_json' ,
    'page arguments' => array(1) ,
    'delivery callback' => 'drupal_json_output' ,
  );
  return $items;
}

function data_dashboard_export_json($wabe) {
  $alias = "wabe/$wabe";
  $path = drupal_lookup_path("source", $alias);
  $node = menu_get_object("node", 1, $path);

  $datensatz_id = $node->datenwabe_dataset['und'][0]['nid'];
  $datensatz_path = drupal_get_path_alias("node/" . $datensatz_id);

  $result = array();
  
  $result['portal'] = array();
  $result['portal']['title'] = $node->title;
  $result['portal']['url'] = $datensatz_path;

  $result['front'] = array();
  $result['front']['textTop'] = $node->datenwabe_front_text_top['und'][0]['value'];
  $result['front']['textBottom'] = $node->datenwabe_front_text_bottom['und'][0]['value'];
  $result['front']['value'] = $node->datenwabe_front_value['und'][0]['value'];
  $result['front']['unit'] = $node->datenwabe_front_unit['und'][0]['value'];
  $result['front']['changePerDay'] = $node->datenwabe_front_change_per_day['und'][0]['value'];
  $result['front']['format'] = $node->datenwabe_front_format['und'][0]['value'];
  $result['front']['background'] = $node->datenwabe_front_background['und'][0]['value'];
  $result['front']['color'] = $node->datenwabe_front_color['und'][0]['value'];


  $result['back'] = array();
  $result['back']['text'] = $node->datenwabe_back_text['und'][0]['value'];
  $result['back']['color'] = $node->datenwabe_back_color['und'][0]['value'];
  $result['back']['cssClass'] = $node->datenwabe_back_css_class['und'][0]['value'];
  $result['back']['background'] = $node->datenwabe_back_background['und'][0]['value'];

  return $result;
}